

SELECT SUM(g.SCORE) AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_GRADE g JOIN HR_EMPLOYEES e ON g.EMP_NO = e.EMP_NO
WHERE g.YEAR = '2022'
GROUP BY e.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;